### ISSUE TITLE
Panic and Segmentation error when accessing secret via Google Provider on k8s pod

### ISSUE THREAD

**Issue by saranicole** [doitintl/secrets-init#1]
I am using the following deployment file

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secretmanagerdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: secretmanagerdemo
    spec:
      initContainers:
        - name: secrets-init
          image: doitintl/secrets-init:v0.2.4
          command:
            - sh
          args:
            - -c
            - "cp /usr/local/bin/secrets-init /secrets-init/bin/"
          volumeMounts:
            - mountPath: /secrets-init/bin
              name: secrets-init-volume
      containers:
        - image: alpine:3
          name: print-env
          env:
            - name: TEST_SECRET
              value: gcp:secretmanager:projects/$PROJECT_ID/secrets/testsecret
          command:
            - /secrets-init/bin/secrets-init
          args:
            - --provider
            - google
            - sh
            - -c
            - 'echo $TEST_SECRET'
          volumeMounts:
            - mountPath: /secrets-init/bin
              name: secrets-init-volume
      volumes:
        - name: secrets-init-volume
          emptyDir: {}
```

I am getting the expected output of the secret value but the container is exiting with an error due to the following:

```
/$ POD=secretmanagerdemo-6ff8dd4d4b-vgjvm
/$ kubectl logs -f $POD --all-containers
testing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xad45ad]

goroutine 62 [running]:
main.run.func1(0xc0000ab680, 0xc0000d14a0)
	/home/runner/work/secrets-init/secrets-init/main.go:155 +0xad
created by main.run
	/home/runner/work/secrets-init/secrets-init/main.go:150 +0x363
```

Any ideas?  Thanks in advance
