### ISSUE TITLE
Environment variable value not inherited in child process or application container.

### ISSUE THREAD

**Issue by hareacc** [doitintl/secrets-init#29]
I used below snippet. After pod/container get created, I can manually run aws cli with secrets manager command and it worked so means, service account, aws iam role is correct but still not found variable value in /tmp/xyz as per command or not in log or not when ran manually echo $MY_PASSWORD. What's wrong?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekssecrettest
  namespace: dev  
  labels:
    app: ekssecrettest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekssecrettest
  template:
    metadata:
      labels:
        app: ekssecrettest
    spec:
      serviceAccountName: ekssecrettest
      restartPolicy: Always      
      initContainers: 
        - name: ekssecrettest
          image: 'doitintl/secrets-init:latest'
          env:
            - name: MY_PASSWORD
              value: arn:aws:secretsmanager:eu-central-1:111111111111:secret:ekssecrettest-5zaSrq    
      containers:
        - name: awscli
          image: 'amazon/aws-cli'
          command: ["/bin/sh","-c"]
          args: ["echo $MY_PASSWORD >> /tmp/xyz; sleep 365d"]
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi              

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ekssecrettest
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/ekssecrettest
```
